# Désactiver la vérification SSL
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=NONE -Djavax.net.ssl.trustStoreType=Windows-ROOT
android.useAndroidX=true
android.enableJetifier=true

# Ignorer les erreurs SSL
systemProp.javax.net.ssl.trustStore=C:\\Windows\\win.ini
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
systemProp.org.gradle.internal.http.sslRetry=true

# Utiliser HTTP au lieu de HTTPS
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=

# Timeouts plus longs
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.http.connectionTimeout=120000


